name: Test
on:
  workflow_call:
    inputs:
      python-versions:
        description: 'JSON array of Python versions to test'
        required: false
        type: string
        default: '["3.9", "3.10", "3.11", "3.12"]'
      run-linting:
        description: 'Whether to run linting checks'
        required: false
        type: boolean
        default: true
      test-build:
        description: 'Whether to test package build'
        required: false
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run linting
        if: inputs.run-linting
        run: ruff check src/ test/
      - name: Run tests
        run: pytest -v test/
      - name: Test CLI commands
        run: |
          awair --help
          awair data --help
          awair api --help
          awair lambda --help
      - name: Test package build
        if: inputs.test-build
        run: |
          pip install build
          python -m build
          pip install dist/*.whl
          awair --help
